---
apiVersion: v1
kind: Service
metadata:
  name: automation-university-department
  labels:
    app: automation-university
spec:
  ports:
    - port: 80
      targetPort: 80
      name: web-http
    - port: 443
      targetPort: 443
      name: web-https
    - port: 8083
      targetPort: 8083
      name: micro-port
  selector:
    app: automation-university
    tier: webservice
  clusterIP: None
  #---
  #apiVersion: v1
  #kind: PersistentVolumeClaim
  #metadata:
  #  name: mysql-pv-claim
  #  labels:
  #    app: automation-university
  #spec:
  #  accessModes:
  #    - ReadWriteOnce
  #  resources:
  #    requests:
  #      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-university-department
  labels:
    app: automation-university
spec:
  selector:
    matchLabels:
      app: automation-university
      tier: webservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: automation-university
        tier: webservice
    spec:
      containers:
        - image: automationu/department-service:0.0.1-SNAPSHOT
          name: department-service
          ports:
            - containerPort: 443
            - containerPort: 80
              name: department
          imagePullPolicy: Always
#          volumeMounts:
#            - name: mysql-persistent-storage
#              mountPath: /var/lib/mysql
#      volumes:
#        - name: mysql-persistent-storage
#          persistentVolumeClaim:
#            claimName: mysql-pv-claim
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#  name: mysql-pass
# type: Opaque
# data:
#  password: bXktc3VwZXItc2VjcmV0LXBhc3N3b3Jk
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: c3ByaW5nVXNlcg==
  password: bXktc3VwZXItc2VjcmV0LXBhc3N3b3Jk
