---
apiVersion: v1
kind: Service
metadata:
  name: automation-university-mysql
  labels:
    app: automation-university
spec:
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: automation-university
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: automation-university
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-university-mysql
  labels:
    app: automation-university
spec:
  selector:
    matchLabels:
      app: automation-university
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: automation-university
        tier: mysql
    spec:
      containers:
        - image: mysql/mysql-server:latest
          name: mysql
          env:
            - name: DB_HOST
              value: 127.0.0.1
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: bXktc3VwZXItc2VjcmV0LXBhc3N3b3Jk
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: mysql-db-svc
  namespace: automation-university
subsets:
  - addresses:
      - ip: "10.10.1.1"
    ports:
      - port: 3306
