---
version: '3.8'
services:
  database:
    container_name: automation-university-database
    image: 'library/mysql:latest'
#    build:
#      context: ./
#      dockerfile: Dockerfile.mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=university-department-db
      - MYSQL_USER=springUser
      - MYSQL_ROOT_HOST=%
    networks:
      - automation-unversity-network
    volumes:
      - $PWD/data/mysql:/var/lib/mysql
#    healthcheck:
#      test: /usr/bin/mysql --user=springUser --password=ThePassword --execute "SHOW DATABASES;"
#      interval: 2s
#      timeout: 20s
#      retries: 10
  microservice:
    container_name: department-service
    #image: 'automationu/department-service:0.0.1-SNAPSHOT'
    build:
      args:
        - JAR_FILE=department-service-0.0.1-SNAPSHOT.jar
      context: ./
      dockerfile: Dockerfile.maven
    ports:
      - '8083:8083'
    depends_on:
      - database
    networks:
      - automation-unversity-network
networks:
  automation-unversity-network:
    driver: bridge
volumes:
  db-data: null
