version: '3.8'
services:
  database:
    container_name: automation-university-database
    image: 'library/mysql:latest'
    restart: always
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=university-department-db
      - MYSQL_USER=springuser
    networks:
      - automation-unversity-network
    volumes:
      - db-data:/~/Documents/Docker/Spring
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
#  hibernate-app:
#    container_name: db-init
#    build:
#      context: ./database
#      dockerfile: Dockerfile
#    #restart: on-failure
#    volumes:
#      - gradle-data:/home/gradle/data
#    #      - ./database:./source
#    depends_on:
#      - database
#    networks:
#      - automation-unversity-network
networks:
  automation-unversity-network:
    driver: bridge
volumes:
  db-data: null
  gradle-data: null
